# Generated by Django 5.0.7 on 2025-03-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='description',
            field=models.CharField(default='Your default value here', max_length=255),
        ),
    ]
