# Generated by Django 5.0.7 on 2025-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_branche_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='critere',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='domaine',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
