# Generated by Django 5.0.7 on 2025-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newsletter_newslettersubscriber_date_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
