# Generated by Django 4.2.7 on 2024-07-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcoursFonctionpub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('concours_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcoursFonctionpubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcoursFonctionpubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.concoursfonctionpubcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Concours',
        ),
        migrations.AddField(
            model_name='concoursfonctionpub',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.concoursfonctionpubcategory'),
        ),
        migrations.AddField(
            model_name='concoursfonctionpub',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concours.concoursfonctionpubsubcategory'),
        ),
    ]
