# Generated by Django 4.2.7 on 2024-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0002_concoursfonctionpub_concoursfonctionpubcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcoursGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ConcoursFonctionpub',
            new_name='Concours',
        ),
        migrations.RenameModel(
            old_name='ConcoursFonctionpubCategory',
            new_name='ConcoursCategory',
        ),
        migrations.RenameModel(
            old_name='ConcoursFonctionpubSubCategory',
            new_name='ConcoursSubCategory',
        ),
    ]
