# Generated by Django 4.2.7 on 2024-07-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0003_concoursgroup_rename_concoursfonctionpub_concours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConcoursGroup',
        ),
        migrations.RemoveField(
            model_name='concourssubcategory',
            name='description',
        ),
    ]
