# Generated by Django 4.2.7 on 2024-07-31 09:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0004_delete_concoursgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/concours_images'), upload_to='concours_images'),
        ),
    ]
