# Generated by Django 4.2.7 on 2024-08-01 12:47

import concours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0008_concours_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concours',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=concours.models.upload_to, verbose_name='Image'),
        ),
    ]
