# Generated by Django 4.2.7 on 2024-08-05 13:35

import concours.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0009_alter_concours_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='posts/default.png', upload_to=concours.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='concours',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concours.university'),
        ),
    ]
