# Generated by Django 4.2.7 on 2024-08-06 11:45

import concours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0010_university_concours_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourscategory',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=concours.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='concourssubcategory',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=concours.models.upload_to, verbose_name='Image'),
        ),
    ]
