# Generated by Django 4.2.7 on 2024-08-19 08:01

import concours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0012_alter_concours_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='posts/default.png', upload_to=concours.models.upload_to, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
