# Generated by Django 4.2.7 on 2024-08-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0013_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
    ]
