# Generated by Django 4.2.7 on 2024-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0015_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourssubcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
