# Generated by Django 4.2.7 on 2024-09-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0016_concourssubcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concours',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concours_set', to='concours.concourssubcategory'),
        ),
    ]
