# Generated by Django 4.2.7 on 2024-09-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0017_alter_concours_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcoursDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='concours_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='concours.concours')),
            ],
        ),
    ]
