# Generated by Django 4.2.7 on 2024-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0018_concoursdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='concoursdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='concours_thumbnails/'),
        ),
    ]
