# Generated by Django 4.2.7 on 2024-11-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0019_concoursdocument_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concourssubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='concourssubcategory',
            name='categories',
            field=models.ManyToManyField(related_name='subcategories', to='concours.concourscategory'),
        ),
        migrations.CreateModel(
            name='ConcoursInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concours_date', models.DateField()),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='concours.concours')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concours.university')),
            ],
        ),
    ]
