# Generated by Django 4.2.7 on 2024-11-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0020_remove_concourssubcategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauMinimum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauObtenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='concours',
            name='university',
        ),
        migrations.RemoveField(
            model_name='concoursinstance',
            name='university',
        ),
        migrations.CreateModel(
            name='GrandEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandes_ecoles', to='concours.university')),
            ],
        ),
        migrations.AddField(
            model_name='concours',
            name='grandes_ecoles',
            field=models.ManyToManyField(related_name='concours', to='concours.grandecole'),
        ),
        migrations.AddField(
            model_name='concours',
            name='niveau_minimum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concours_requis', to='concours.niveauminimum'),
        ),
        migrations.AddField(
            model_name='concours',
            name='niveau_obtenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concours_obtenu', to='concours.niveauobtenue'),
        ),
        migrations.AddField(
            model_name='concours',
            name='villes',
            field=models.ManyToManyField(related_name='concours', to='concours.ville'),
        ),
    ]
