# Generated by Django 4.2.7 on 2024-11-11 12:15

import concours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0021_niveauminimum_niveauobtenue_ville_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandecole',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=concours.models.upload_to, verbose_name='Image'),
        ),
    ]
