# Generated by Django 4.2.7 on 2024-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0022_grandecole_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='cycle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concours',
            name='descriptioncycle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
