# Generated by Django 4.2.7 on 2024-11-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0024_cycle_remove_concours_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concours',
            name='cycles',
        ),
        migrations.RemoveField(
            model_name='concoursdocument',
            name='cycle',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
