# Generated by Django 4.2.7 on 2024-11-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0025_remove_concours_cycles_remove_concoursdocument_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='concours',
            name='cycles',
            field=models.ManyToManyField(related_name='concours', to='concours.cycle'),
        ),
        migrations.AddField(
            model_name='concoursdocument',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='concours.cycle'),
        ),
    ]
