# Generated by Django 4.2.7 on 2024-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0026_cycle_concours_cycles_concoursdocument_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='arrondissement',
        ),
        migrations.AddField(
            model_name='ville',
            name='arrondissements',
            field=models.TextField(blank=True, help_text='Séparer les arrondissements par une virgule.', null=True),
        ),
    ]
