# Generated by Django 4.2.7 on 2024-11-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0027_remove_ville_arrondissement_ville_arrondissements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concours',
            name='niveau_obtenue',
        ),
        migrations.AddField(
            model_name='concours',
            name='niveau_obtenu',
            field=models.ManyToManyField(blank=True, related_name='concours_obtenu', to='concours.niveauobtenue'),
        ),
        migrations.RemoveField(
            model_name='concours',
            name='niveau_minimum',
        ),
        migrations.AddField(
            model_name='concours',
            name='niveau_minimum',
            field=models.ManyToManyField(blank=True, related_name='concours_requis', to='concours.niveauminimum'),
        ),
    ]
