# Generated by Django 4.2.7 on 2024-11-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0030_alter_concours_cycles_alter_concours_grandes_ecoles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandecole',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandes_ecoles', to='concours.university'),
        ),
    ]
