# Generated by Django 4.2.7 on 2024-11-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0032_concours_conccours_publication_alter_concours_cycles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concours',
            old_name='conccours_publication',
            new_name='concours_publication',
        ),
    ]
