# Generated by Django 4.2.7 on 2024-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0033_rename_conccours_publication_concours_concours_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourscategory',
            name='description_plus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
