# Generated by Django 5.1.2 on 2025-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0035_alter_searchhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
